package fr.abes.thesesapirecherche.personnes.controller.recherche;

import fr.abes.thesesapirecherche.EnableOnIntegrationTest;
import fr.abes.thesesapirecherche.personnes.controller.PersonneControllerTest;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

public class RechercheTriTest extends PersonneControllerTest {

    @Test
    @DisplayName("Tri A-Z sur la recherche de personnes")
    @EnableOnIntegrationTest
    public void triAZ() throws Exception {
        mockMvc.perform(get("/api/v1/tests/personnes/recherche/?q=*&index=per_recherche_simple_nom_prenom&tri=PersonnesAsc&debut=0&nombre=100"))
                .andExpect(status().isOk())
                // Test la présence des thèses
                .andExpect(jsonPath("$..theses[?(@.nnt=='2011ANGE0040')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2003PA066582')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='1999ROUES082')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2007PA066375')]").exists())
               // .andExpect(jsonPath("$..theses[?(@.nnt=='2017GREAM026')]").exists())
               // .andExpect(jsonPath("$..theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2020REN1B015')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2004BRES2040')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2018LYSE1193')]").exists())
              //  .andExpect(jsonPath("$..theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2020AIXM0184')]").exists())
               // .andExpect(jsonPath("$..theses[?(@.nnt=='2020PA01H073')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='1997PA040286')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='1999ROUES082')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2004BRES2040')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2007PA066375')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='1997PA040286')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2021SORUL154')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2003PA066582')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2011ANGE0040')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2021SORUL154')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2020REN1B015')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$..theses[?(@.nnt=='2020AIXM0184')]").exists())

                // Test l'ordre
                .andExpect(jsonPath("$.personnes[0].theses[?(@.nnt=='2011ANGE0040')]").exists())
                .andExpect(jsonPath("$.personnes[1].theses[?(@.nnt=='2003PA066582')]").exists())
                .andExpect(jsonPath("$.personnes[2].theses[?(@.nnt=='1999ROUES082')]").exists())
                .andExpect(jsonPath("$.personnes[3].theses[?(@.nnt=='2018LYSE1193')]").exists())
                //.andExpect(jsonPath("$.personnes[4].theses[?(@.nnt=='s233939')]").exists())  // Thèse en préparation
                .andExpect(jsonPath("$.personnes[5].theses[?(@.nnt=='2007PA066375')]").exists())
                .andExpect(jsonPath("$.personnes[6].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[7].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[8].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[9].theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$.personnes[10].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[11].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[12].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[13].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[14].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[15].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[16].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[17].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[18].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[19].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[20].theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$.personnes[21].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[22].theses[?(@.nnt=='2020REN1B015')]").exists())
                .andExpect(jsonPath("$.personnes[23].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[24].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[25].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[26].theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$.personnes[27].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[28].theses[?(@.nnt=='2004BRES2040')]").exists())
                .andExpect(jsonPath("$.personnes[29].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[30].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[31].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[32].theses[?(@.nnt=='2020PA01H073')]").exists())
                .andExpect(jsonPath("$.personnes[33].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[34].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[35].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[36].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[37].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[38].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[39].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[40].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[41].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[42].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[43].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[44].theses[?(@.nnt=='1997PA040286')]").exists())
                .andExpect(jsonPath("$.personnes[45].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[46].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[47].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[48].theses[?(@.nnt=='1999ROUES082')]").exists())
                .andExpect(jsonPath("$.personnes[49].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[50].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[51].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[52].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[53].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[54].theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$.personnes[55].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[56].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[57].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[58].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[59].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[60].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[61].theses[?(@.nnt=='2004BRES2040')]").exists())
                .andExpect(jsonPath("$.personnes[62].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[63].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[64].theses[?(@.nnt=='2017GREAM026')]").exists())
                //.andExpect(jsonPath("$.personnes[65].theses[?(@.nnt=='s347820')]").exists())  // Thèse en préparation
                .andExpect(jsonPath("$.personnes[66].theses[?(@.nnt=='2007PA066375')]").exists())
                .andExpect(jsonPath("$.personnes[67].theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$.personnes[68].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[69].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[70].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[71].theses[?(@.nnt=='1997PA040286')]").exists())
                .andExpect(jsonPath("$.personnes[72].theses[?(@.nnt=='2020PA01H073')]").exists())
                .andExpect(jsonPath("$.personnes[73].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[74].theses[?(@.nnt=='2021SORUL154')]").exists())
                .andExpect(jsonPath("$.personnes[75].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[76].theses[?(@.nnt=='2003PA066582')]").exists())
                .andExpect(jsonPath("$.personnes[77].theses[?(@.nnt=='2011ANGE0040')]").exists())
               // .andExpect(jsonPath("$.personnes[78].theses[?(@.nnt=='s233939')]").exists())  // Thèse en préparation
                .andExpect(jsonPath("$.personnes[79].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[80].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[81].theses[?(@.nnt=='2021SORUL154')]").exists())
                .andExpect(jsonPath("$.personnes[82].theses[?(@.nnt=='2020REN1B015')]").exists())
                .andExpect(jsonPath("$.personnes[83].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[84].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[85].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[86].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[87].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[88].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[89].theses[?(@.nnt=='2018LYSE1193')]").exists())
               // .andExpect(jsonPath("$.personnes[90].theses[?(@.nnt=='s347820')]").exists())  // Thèse en préparation
                .andExpect(jsonPath("$.personnes[91].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[92].theses[?(@.nnt=='2020AIXM0184')]").exists());
    }

    @Test
    @DisplayName("Tri Z-A sur la recherche de personnes")
    @EnableOnIntegrationTest
    public void triZA() throws Exception {
        mockMvc.perform(get("/api/v1/tests/personnes/recherche/?q=*&index=per_recherche_simple_nom_prenom&tri=PersonnesDesc"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.personnes[0].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[1].theses[?(@.nnt=='2021AIXM0253')]").exists())
                //.andExpect(jsonPath("$.personnes[2].theses[?(@.nnt=='s347820')]").exists())  // Thèse en préparation
                .andExpect(jsonPath("$.personnes[3].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[4].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[5].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[6].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[7].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[8].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[9].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[10].theses[?(@.nnt=='2020REN1B015')]").exists())
                .andExpect(jsonPath("$.personnes[11].theses[?(@.nnt=='2021SORUL154')]").exists())
                .andExpect(jsonPath("$.personnes[12].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[13].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[14].theses[?(@.nnt=='2004BRES2040')]").exists())
                .andExpect(jsonPath("$.personnes[15].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[16].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[17].theses[?(@.nnt=='2017GREAM026')]").exists())
               // .andExpect(jsonPath("$.personnes[18].theses[?(@.nnt=='s347820')]").exists()) // Thèse en préparation
                .andExpect(jsonPath("$.personnes[19].theses[?(@.nnt=='2007PA066375')]").exists())
                .andExpect(jsonPath("$.personnes[20].theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$.personnes[21].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[22].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[23].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[24].theses[?(@.nnt=='1997PA040286')]").exists())
                .andExpect(jsonPath("$.personnes[25].theses[?(@.nnt=='2020PA01H073')]").exists())
                .andExpect(jsonPath("$.personnes[26].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[27].theses[?(@.nnt=='2021SORUL154')]").exists())
                .andExpect(jsonPath("$.personnes[28].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[29].theses[?(@.nnt=='2003PA066582')]").exists())
                .andExpect(jsonPath("$.personnes[30].theses[?(@.nnt=='2011ANGE0040')]").exists())
                //.andExpect(jsonPath("$.personnes[31].theses[?(@.nnt=='s233939')]").exists())  // Thèse en préparation
                .andExpect(jsonPath("$.personnes[32].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[33].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[34].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[35].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[36].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[37].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[38].theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$.personnes[39].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[40].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[41].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[42].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[43].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[44].theses[?(@.nnt=='1999ROUES082')]").exists())
                .andExpect(jsonPath("$.personnes[45].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[46].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[47].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[48].theses[?(@.nnt=='1997PA040286')]").exists())
                .andExpect(jsonPath("$.personnes[49].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[50].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[51].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[52].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[53].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[54].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[55].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[56].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[57].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[58].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[59].theses[?(@.nnt=='2017ECLI0025')]").exists())
                .andExpect(jsonPath("$.personnes[60].theses[?(@.nnt=='2020PA01H073')]").exists())
                .andExpect(jsonPath("$.personnes[61].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[62].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[63].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[64].theses[?(@.nnt=='2004BRES2040')]").exists())
                .andExpect(jsonPath("$.personnes[65].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[66].theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$.personnes[67].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[68].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[69].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[70].theses[?(@.nnt=='2020REN1B015')]").exists())
                .andExpect(jsonPath("$.personnes[71].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[72].theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$.personnes[73].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[74].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[75].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[76].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[77].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[78].theses[?(@.nnt=='2017PA01H038')]").exists())
                .andExpect(jsonPath("$.personnes[79].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[80].theses[?(@.nnt=='2019LYSE2095')]").exists())
                .andExpect(jsonPath("$.personnes[81].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[82].theses[?(@.nnt=='2016SACLN057')]").exists())
                .andExpect(jsonPath("$.personnes[83].theses[?(@.nnt=='2019LYSES011')]").exists())
                .andExpect(jsonPath("$.personnes[84].theses[?(@.nnt=='2020AIXM0184')]").exists())
                .andExpect(jsonPath("$.personnes[85].theses[?(@.nnt=='2021AIXM0253')]").exists())
                .andExpect(jsonPath("$.personnes[86].theses[?(@.nnt=='2017GREAM026')]").exists())
                .andExpect(jsonPath("$.personnes[87].theses[?(@.nnt=='2007PA066375')]").exists())
                //.andExpect(jsonPath("$.personnes[88].theses[?(@.nnt=='s233939')]").exists())  // Thèse en préparation
                .andExpect(jsonPath("$.personnes[89].theses[?(@.nnt=='2018LYSE1193')]").exists())
                .andExpect(jsonPath("$.personnes[90].theses[?(@.nnt=='1999ROUES082')]").exists())
                .andExpect(jsonPath("$.personnes[91].theses[?(@.nnt=='2003PA066582')]").exists())
                .andExpect(jsonPath("$.personnes[92].theses[?(@.nnt=='2011ANGE0040')]").exists());
    }
}
