facets:
  main:
    - libelle: Statut
      champ: status
      searchBar: false
    - libelle: Etablissements
      champ: etabSoutenanceN.exact
    - libelle: Domaines thématique
      champ: oaiSetNames
      searchBar: true
    - libelle: Discipline
      champ: discipline.exact
      searchBar: true
    - libelle: Langues
      champ: langues
      searchBar: true
    - libelle: Ecole doctorale
      champ: ecolesDoctoralesN.exact
      searchBar: true
  subs:
    - libelle: Accessible en ligne
      champ: accessible
      parentName: soutenue