facets:
  mainTheses:
    - libelle: Statut
      champ: status
      searchBar: false
    - libelle: Établissements
      champ: etabSoutenanceN.exact
      searchBar: true
    - libelle: Domaines thématiques
      champ: oaiSetNames
      searchBar: true
    - libelle: Disciplines
      champ: discipline.exact
      searchBar: true
    - libelle: Langues
      champ: langues
      searchBar: true
    - libelle: Écoles doctorales
      champ: ecolesDoctoralesN.exact
      searchBar: true
  subsTheses:
    - libelle: Accessibles en ligne
      champ: accessible
      parentName: soutenue
  mainPersonnes:
    - libelle: Role
      champ: roles
      searchBar: true
    - libelle: Établissements
      champ: etablissements
      searchBar: true
    - libelle: Domaines thématiques
      champ: domaines
      searchBar: true
